In [ ]:
import csv
from faker import Faker
fake=Faker('en_IN')
methods={
    'uid':lambda:'IQ-'+"".join(random.choices(string.digits+string.ascii_uppercase,k=5),
    'first_name':fake.first_name,
    'last_name':fake.last_name,
    'email':fake:email,
    'phone_number':fake.phone_number,
    'city':fake.city,
    'state':fake.state,
    'country':fake.country,
    'random_number':fake.random_number,
    'date':fake.date_time,
    'salary':lambda:random.randrange(200000,1000000)
}
def create_csv_data():
    print("------------Creating Csv Dataset--------------")
    file_name=input("Enter your file name without extension")+".csv"
    try:
        num_rows=int(input("Enter number of rows :"))
        if num_rows<=0:
            raise ValueError
        except ValueError as e: 
            print("

In [4]:
from faker import Faker
import pandas as pd

# Initialize Faker
fake = Faker()
fake=Faker('en_IN')

# Number of rows to generate
num_rows = 100

# Create a list to store the data
data = []

# Generate fake data
for _ in range(num_rows):
    row = {
        "Name": fake.name(),
        "Email": fake.email(),
        "Phone Number": fake.phone_number(),
        "Address": fake.address(),
        "City": fake.city(),
        "State": fake.state(),
        "Postal Code": fake.postcode(),
        "Company": fake.company(),
        "Job Title": fake.job(),
        "Date of Birth": fake.date_of_birth(minimum_age=18, maximum_age=65),
        "Registration Date": fake.date_this_year(),
    }
    data.append(row)

# Convert to DataFrame
df = pd.DataFrame(data)

# Save to CSV (optional)
df.to_csv("fake_dataset.csv", index=False)

# Print the dataset
df

,Name,Email,Phone Number,Address,City,State,Postal Code,Company,Job Title,Date of Birth,Registration Date
0,Zayyan Butala,tgoyal@example.net,+915516477348,84\nSetty Ganj\nAligarh-368999,North Dumdum,Arunachal Pradesh,178382,Atwal-Verma,Chief Technology Officer,1998-05-02,2025-01-03
1,Faraj Cheema,dipta60@example.com,7591850052,"87, Sampath Street\nAjmer 894249",Ludhiana,Rajasthan,384923,Issac-Chandra,"Accountant, chartered management",1980-10-10,2025-01-05
2,Vasatika Deshmukh,zdash@example.com,+913021017676,"H.No. 875, Bhagat Marg\nEtawah-452053",Agra,Tamil Nadu,493627,Hayre Inc,Phytotherapist,1971-04-20,2025-01-03
3,Tarak Soman,srinivassara@example.com,03342808276,60/792\nSamra Nagar\nMalegaon 848365,Patiala,Sikkim,740839,Mistry-Puri,Private music teacher,1993-02-27,2025-01-05
4,Daksha Agrawal,kabirdeol@example.com,+915218558311,918\nKamdar Path\nSecunderabad-140590,Chapra,Bihar,398794,"Hari, Bedi and Dave",Metallurgist,1983-02-18,2025-01-06
...,...,...,...,...,...,...,...,...,...,...,...
95,Aarnav Raghavan,trivediamol@example.org,8029353301,26/881\nMallick Road\nGopalpur 085863,Nagaon,Uttarakhand,618394,Mohan-Choudhary,Housing manager/officer,1987-05-13,2025-01-03
96,Qabil Dhar,cvala@example.net,+917473409665,"00, More Street\nNangloi Jat 888017",Panchkula,Telangana,270208,Desai-Rajagopal,Nutritional therapist,1982-06-06,2025-01-09
97,Manthan Bhat,darpan16@example.org,4325569048,"H.No. 19, Hora Street, Farrukhabad 404543",Tadepalligudem,Mizoram,471628,Patla PLC,"Pilot, airline",1986-10-29,2025-01-07
98,Gaurav Tripathi,widisharout@example.org,01068277828,"H.No. 01, Agarwal Street, Thrissur 575595",Berhampur,Chhattisgarh,340721,Sarin-Tata,"Engineer, maintenance (IT)",1988-05-18,2025-01-06
99,Irya Yadav,ygour@example.org,7558426303,"21, Raj Road, Karaikudi-566216",Kanpur,West Bengal,453610,Dhar PLC,Podiatrist,2004-01-27,2025-01-04

In [5]:
from faker import Faker
import pandas as pd

# Initialize Faker
fake = Faker()

# Number of rows to generate
num_rows = 100

# Create a list to store the data
data = []

# Generate fake data
for _ in range(num_rows):
    row = {
        "Name": fake.name(),
        "Email": fake.email(),
        "Phone Number": fake.phone_number(),
        "Address": fake.address(),
        "City": fake.city(),
        "State": fake.state(),
        "Country": fake.country(),
        "Postal Code": fake.postcode(),
        "Company": fake.company(),
        "Job Title": fake.job(),
        "Date of Birth": fake.date_of_birth(minimum_age=18, maximum_age=65),
        "Registration Date": fake.date_this_year(),
    }
    data.append(row)

# Convert to DataFrame
df = pd.DataFrame(data)

# Save to Excel
df.to_excel("fake_dataset.xlsx", index=False)

# Print confirmation message
print("Dataset saved as 'fake_dataset.xlsx'")

Dataset saved as 'fake_dataset.xlsx'